export const REGION = [
    { name: 'ARIANA' },
    { name: 'BÉJA' },
    { name: 'BEN AROUS' },
    { name: 'BIZERTE' },
    { name: 'EL KEF' },
    { name: 'GABES' },
    { name: 'GAFSA' },
    { name: 'JENDOUBA' },
    { name: 'KAIROUAN' },
    { name: 'KESSERINE' },
    { name: 'KEBILI' },
    { name: 'MAHDIA' },
    { name: 'MANOUBA' },
    { name: 'MEDENINE' },
    { name: 'MONASTIR' },
    { name: 'NABEUL' },
    { name: 'SFAX' },
    { name: 'SIDI BOUZID' },
    { name: 'SILIANA' },
    { name: 'SOUSSE' },
    { name: 'TATAOUINE' },
    { name: 'TOZEUR' },
    { name: 'TUNIS' },
    { name: 'ZAGHOUAN' },
];
